In [44]:
import pandas as pd
import numpy as np
import joblib as jb

In [23]:
file_path = "../../Data/raw/wine.data"
column_names = [
    "Class",
    "Alcohol",
    "Malic_Acid",
    "Ash",
    "Alcalinity_of_Ash",
    "Magnesium",
    "Total_Phenols",
    "Flavanoids",
    "Nonflavanoid_Phenols",
    "Proanthocyanins",
    "Color_Intensity",
    "Hue",
    "OD280_OD315",
    "Proline"
]
wine = pd.read_csv(file_path,names = column_names, header = None)
wine

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [24]:
wine.isna().sum()

Class                   0
Alcohol                 0
Malic_Acid              0
Ash                     0
Alcalinity_of_Ash       0
Magnesium               0
Total_Phenols           0
Flavanoids              0
Nonflavanoid_Phenols    0
Proanthocyanins         0
Color_Intensity         0
Hue                     0
OD280_OD315             0
Proline                 0
dtype: int64

In [25]:
wine.duplicated().sum()

np.int64(0)

In [26]:
wine.dtypes

Class                     int64
Alcohol                 float64
Malic_Acid              float64
Ash                     float64
Alcalinity_of_Ash       float64
Magnesium                 int64
Total_Phenols           float64
Flavanoids              float64
Nonflavanoid_Phenols    float64
Proanthocyanins         float64
Color_Intensity         float64
Hue                     float64
OD280_OD315             float64
Proline                   int64
dtype: object

In [27]:
wine.columns.to_list()

['Class',
 'Alcohol',
 'Malic_Acid',
 'Ash',
 'Alcalinity_of_Ash',
 'Magnesium',
 'Total_Phenols',
 'Flavanoids',
 'Nonflavanoid_Phenols',
 'Proanthocyanins',
 'Color_Intensity',
 'Hue',
 'OD280_OD315',
 'Proline']

In [28]:
wine = wine.drop(columns=["Class"])

In [29]:
wine.head()

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [30]:
wine.tail()

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560

In [31]:
print(wine[wine["Alcohol"] < 0].sum())

Q1 = wine["Alcohol"].quantile(0.25)
Q3 = wine["Alcohol"].quantile(0.75)

IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Alcohol"] < lower_bound) | (wine["Alcohol"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

Empty DataFrame
Columns: [Alcohol, Malic_Acid, Ash, Alcalinity_of_Ash, Magnesium, Total_Phenols, Flavanoids, Nonflavanoid_Phenols, Proanthocyanins, Color_Intensity, Hue, OD280_OD315, Proline]
Index: []

In [32]:
print(wine[wine["Malic_Acid"] < 0].sum())

Q1 = wine["Malic_Acid"].quantile(0.25)
Q3 = wine["Malic_Acid"].quantile(0.75)

IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Malic_Acid"] < lower_bound) | (wine["Malic_Acid"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
123,13.05,5.80,2.13,21.5,86,2.62,2.65,0.30,2.01,2.6,0.73,3.10,380
137,12.53,5.51,2.64,25.0,96,1.79,0.60,0.63,1.10,5.0,0.82,1.69,515
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740

In [33]:
print(wine[wine["Alcalinity_of_Ash"] < 0].sum())

Q1 = wine["Alcalinity_of_Ash"].quantile(0.25)
Q3 = wine["Alcalinity_of_Ash"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Alcalinity_of_Ash"] < lower_bound) | (wine["Alcalinity_of_Ash"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
59,12.37,0.94,1.36,10.6,88,1.98,0.57,0.28,0.42,1.95,1.05,1.82,520
73,12.99,1.67,2.60,30.0,139,3.30,2.89,0.21,1.96,3.35,1.31,3.50,985
121,11.56,2.05,3.23,28.5,119,3.18,5.08,0.47,1.87,6.00,0.93,3.69,465
127,11.79,2.13,2.78,28.5,92,2.13,2.24,0.58,1.76,3.00,0.97,2.44,466

In [34]:
print(wine[wine["Magnesium"] < 0].sum())

Q1 = wine["Magnesium"].quantile(0.25)
Q3 = wine["Magnesium"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Magnesium"] < lower_bound) | (wine["Magnesium"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
69,12.21,1.19,1.75,16.8,151,1.85,1.28,0.14,2.50,2.85,1.28,3.07,718
73,12.99,1.67,2.60,30.0,139,3.30,2.89,0.21,1.96,3.35,1.31,3.50,985
78,12.33,0.99,1.95,14.8,136,1.90,1.85,0.35,2.76,3.40,1.06,2.31,750
95,12.47,1.52,2.20,19.0,162,2.50,2.27,0.32,3.28,2.60,1.16,2.63,937

In [35]:
print(wine[wine["Total_Phenols"]<0].sum())

Q1 = wine["Total_Phenols"].quantile(0.25)
Q3 = wine["Total_Phenols"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Total_Phenols"] < lower_bound) | (wine["Total_Phenols"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

Empty DataFrame
Columns: [Alcohol, Malic_Acid, Ash, Alcalinity_of_Ash, Magnesium, Total_Phenols, Flavanoids, Nonflavanoid_Phenols, Proanthocyanins, Color_Intensity, Hue, OD280_OD315, Proline]
Index: []

In [36]:
print(wine[wine["Flavanoids"] < 0].sum())

Q1 = wine["Flavanoids"].quantile(0.25)
Q3 = wine["Flavanoids"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Flavanoids"] < lower_bound) | (wine["Flavanoids"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

Empty DataFrame
Columns: [Alcohol, Malic_Acid, Ash, Alcalinity_of_Ash, Magnesium, Total_Phenols, Flavanoids, Nonflavanoid_Phenols, Proanthocyanins, Color_Intensity, Hue, OD280_OD315, Proline]
Index: []

In [37]:
print(wine[wine["Nonflavanoid_Phenols"] < 0].sum())

Q1 = wine["Nonflavanoid_Phenols"].quantile(0.25)
Q3 = wine["Nonflavanoid_Phenols"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Nonflavanoid_Phenols"] < lower_bound) | (wine["Nonflavanoid_Phenols"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

Empty DataFrame
Columns: [Alcohol, Malic_Acid, Ash, Alcalinity_of_Ash, Magnesium, Total_Phenols, Flavanoids, Nonflavanoid_Phenols, Proanthocyanins, Color_Intensity, Hue, OD280_OD315, Proline]
Index: []

In [38]:
print(wine[(wine["Proanthocyanins"] < 0)].sum())

Q1 = wine["Proanthocyanins"].quantile(0.25)
Q3 = wine["Proanthocyanins"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Proanthocyanins"] < lower_bound) | (wine["Proanthocyanins"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
95,12.47,1.52,2.20,19.0,162,2.50,2.27,0.32,3.28,2.6,1.16,2.63,937
110,11.46,3.74,1.82,19.5,107,3.18,2.58,0.24,3.58,2.9,0.75,2.81,562

In [39]:
print(wine[(wine["Color_Intensity"] < 0)].sum())

Q1 = wine["Color_Intensity"].quantile(0.25)
Q3 = wine["Color_Intensity"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Color_Intensity"] < lower_bound) | (wine["Color_Intensity"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
151,12.79,2.67,2.48,22.0,112,1.48,1.36,0.24,1.26,10.80,0.48,1.47,480
158,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660
159,13.48,1.67,2.64,22.5,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620
166,13.45,3.70,2.60,23.0,111,1.70,0.92,0.43,1.46,10.68,0.85,1.56,695

In [40]:
print(wine[wine["Hue"] < 0].sum())

Q1 = wine["Hue"].quantile(0.25)
Q3 = wine["Hue"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[(wine["Hue"] < lower_bound) | (wine["Hue"] > higher_bound)]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
115,11.03,1.51,2.2,21.5,85,2.46,2.17,0.52,2.01,1.9,1.71,2.87,407

In [41]:
print(wine[(wine["OD280_OD315"] < 0)].sum())

Q1 = wine["OD280_OD315"].quantile(0.25)
Q3 = wine["OD280_OD315"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[wine["OD280_OD315"]< lower_bound] | wine[wine["OD280_OD315"] > higher_bound]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

Empty DataFrame
Columns: [Alcohol, Malic_Acid, Ash, Alcalinity_of_Ash, Magnesium, Total_Phenols, Flavanoids, Nonflavanoid_Phenols, Proanthocyanins, Color_Intensity, Hue, OD280_OD315, Proline]
Index: []

In [42]:
print(wine[(wine["Proline"] < 0)].sum())

Q1 = wine["Proline"].quantile(0.25)
Q3 = wine["Proline"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
higher_bound = Q3 + 1.5 * IQR

wine[wine["Proline"]< lower_bound] | wine[wine["Proline"]> higher_bound]

Alcohol                 0.0
Malic_Acid              0.0
Ash                     0.0
Alcalinity_of_Ash       0.0
Magnesium               0.0
Total_Phenols           0.0
Flavanoids              0.0
Nonflavanoid_Phenols    0.0
Proanthocyanins         0.0
Color_Intensity         0.0
Hue                     0.0
OD280_OD315             0.0
Proline                 0.0
dtype: float64

Empty DataFrame
Columns: [Alcohol, Malic_Acid, Ash, Alcalinity_of_Ash, Magnesium, Total_Phenols, Flavanoids, Nonflavanoid_Phenols, Proanthocyanins, Color_Intensity, Hue, OD280_OD315, Proline]
Index: []

In [47]:
wine.to_csv("../../Data/interm/wine_cleaned.csv", index = False)